### ISSUE TITLE
parse history lines; create statute stubs

### ISSUE THREAD

**Issue by dgreisen-cfpb** [DCCouncil/dc-law#3]
blocked by #2.

Each section has a history line. We need to pull the dc statute cites from the history line and generate a stub statute node for each statute that has modified the code.

This should be done in the `make_statutes` script that I've already stubbed out: https://github.com/DCCouncil/dc-law-tools/blob/master/process_xml_jobs/annotation_transforms/make_statutes.py

See the make_statutes docstring for more info on the structure of the stub annotation node.

**Comment by thadk** [comment]
Here are two useful links for the parsing regex's.
https://github.com/openlawdc/simple-generator/blob/master/render_body.js
https://github.com/unitedstates/citation/blob/master/citations/dc_law.js

**Comment by dgreisen-cfpb** [comment]
closed by https://github.com/DCCouncil/dc-law-tools/commit/b7c7cb115e2bb7307fe4787f9b36626e38f44f8f
